# Generated by Django 4.2.30 on 2026-05-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_no', models.CharField(max_length=50, unique=True)),
                ('functional_area_code', models.CharField(max_length=50)),
                ('functional_area_name', models.CharField(max_length=255)),
                ('standard_no', models.CharField(max_length=50)),
                ('standard_code', models.CharField(max_length=50)),
                ('standard_title', models.CharField(max_length=500)),
                ('indicator_text', models.TextField()),
                ('compliance_requirement', models.TextField(blank=True, null=True)),
                ('surveyor_check', models.TextField(blank=True, null=True)),
                ('scoring_note', models.TextField(blank=True, null=True)),
                ('max_score', models.IntegerField(default=10)),
                ('weightage_percent', models.IntegerField(default=100)),
                ('partial_allowed', models.BooleanField(default=False)),
                ('partial_score_percent', models.IntegerField(default=80)),
                ('source_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
