# Generated by Django 5.2.14 on 2026-05-18 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_no', models.CharField(max_length=50, unique=True)),
                ('functional_area_code', models.CharField(blank=True, max_length=50)),
                ('functional_area_name', models.CharField(blank=True, max_length=255)),
                ('standard_no', models.CharField(blank=True, max_length=50)),
                ('standard_code', models.CharField(blank=True, max_length=50)),
                ('standard_title', models.CharField(blank=True, max_length=255)),
                ('indicator_text', models.TextField()),
                ('max_score', models.IntegerField(default=10)),
                ('weightage_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('compliance_requirement', models.TextField(blank=True)),
                ('surveyor_check', models.TextField(blank=True)),
                ('required_evidence', models.TextField(blank=True)),
                ('evidence_category', models.CharField(blank=True, max_length=100)),
                ('register_required', models.BooleanField(default=False)),
                ('register_name', models.CharField(blank=True, max_length=255)),
                ('recurring_required', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(blank=True, max_length=50)),
                ('document_to_generate', models.CharField(blank=True, max_length=255)),
                ('physical_action_required', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=True)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_status', models.CharField(choices=[('missing', 'Missing'), ('partial', 'Partial'), ('ready', 'Ready'), ('verified', 'Verified'), ('not_applicable', 'Not Applicable')], default='missing', max_length=50)),
                ('current_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('gap_summary', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('evidence_location', models.CharField(blank=True, max_length=255)),
                ('ready_for_print_pack', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='indicators.indicator')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
