# Generated by Django 6.0.7 on 2026-08-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('phc_registration_no', models.CharField(max_length=64)),
                ('supervising_pathologist', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Lab Profile',
                'verbose_name_plural': 'Lab Profile',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_no', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standards', to='registry.domain')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('weightage', models.PositiveSmallIntegerField()),
                ('allows_partial', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('one_time', 'One-time'), ('recurring', 'Recurring')], max_length=16)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Biannual'), ('annual', 'Annual'), ('as_needed', 'As needed')], max_length=16, null=True)),
                ('evidence_format', models.CharField(choices=[('photo', 'Photo'), ('document', 'Document'), ('structured_form', 'Structured form')], max_length=32)),
                ('compliance_requirements', models.JSONField(default=list)),
                ('survey_process', models.JSONField(default=list)),
                ('scoring', models.JSONField(default=list)),
                ('guidelines', models.JSONField(default=list)),
                ('retention_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('classification_source', models.CharField(blank=True, max_length=32)),
                ('classification_note', models.TextField(blank=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicators', to='registry.standard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
