# Generated by Django 5.2.17 on 2026-08-06 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LabProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phc_registration_no', models.CharField(max_length=100)),
                ('supervising_pathologist', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lab profile',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_no', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('title', models.TextField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='registry.domain')),
            ],
            options={
                'ordering': ['domain__code', 'standard_no'],
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField(unique=True)),
                ('text', models.TextField()),
                ('weightage', models.PositiveSmallIntegerField(choices=[(100, '100'), (80, '80')])),
                ('allows_partial', models.BooleanField()),
                ('category', models.CharField(choices=[('physical', 'physical'), ('one_time', 'one_time'), ('recurring', 'recurring')], max_length=20)),
                ('frequency', models.CharField(blank=True, choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('biannual', 'biannual'), ('annual', 'annual'), ('as_needed', 'as_needed')], max_length=20, null=True)),
                ('evidence_format', models.CharField(choices=[('photo', 'photo'), ('document', 'document'), ('structured_form', 'structured_form')], max_length=20)),
                ('compliance_requirements', models.JSONField(default=list)),
                ('survey_process', models.JSONField(default=list)),
                ('retention_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='registry.standard')),
            ],
            options={
                'ordering': ['standard__domain__code', 'standard__standard_no', 'source_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='standard',
            constraint=models.UniqueConstraint(fields=('domain', 'standard_no'), name='unique_domain_standard'),
        ),
    ]
