# Generated by Django 5.2.17 on 2026-08-06 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(blank=True, max_length=20, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('fully_met', 'fully_met'), ('partially_met', 'partially_met'), ('not_met', 'not_met')], max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('is_current', models.BooleanField(default=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_records', to='registry.indicator')),
            ],
            options={
                'ordering': ['-submitted_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('indicator', 'period_label'), name='unique_evidence_period')],
            },
        ),
    ]
