# Generated by Django 6.0.7 on 2026-08-02 14:08

import apps.evidence.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_label', models.CharField(blank=True, max_length=16, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('fully_met', 'Fully met'), ('partially_met', 'Partially met'), ('not_met', 'Not met')], max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.evidence.models.evidence_upload_path)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('is_current', models.BooleanField(default=False)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_records', to='registry.indicator')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['indicator', 'period_label'], name='evidence_ev_indicat_f9a5f7_idx'), models.Index(fields=['indicator', 'is_current'], name='evidence_ev_indicat_f3314d_idx')],
            },
        ),
    ]
