# Generated by Django 5.2.17 on 2026-08-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerecord',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m'),
        ),
    ]
