# Generated by Django 6.1 on 2026-08-08 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_evidencerecord_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencerecord',
            name='attachment',
        ),
    ]
