# Generated by Django 5.2.17 on 2026-08-06 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'document'), ('template', 'template')], max_length=20)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('approved', 'approved'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='registry.indicator')),
            ],
        ),
    ]
