# Generated by Django 6.0.7 on 2026-08-02 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('template', 'Template')], max_length=16)),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('reviewed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('version_no', models.PositiveIntegerField(default=1)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='registry.indicator')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
