# Generated by Django 6.0.7 on 2026-08-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drafting', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='draft',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='content',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='indicator',
        ),
        migrations.AddField(
            model_name='draft',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='draft',
            name='indicator_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='draft',
            name='indicators',
            field=models.ManyToManyField(blank=True, related_name='drafts', to='registry.indicator'),
        ),
        migrations.AddField(
            model_name='draft',
            name='linked_document_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draft',
            name='prompt_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='draft',
            name='raw_output',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='draft',
            name='template_version',
            field=models.CharField(default='v1.0', max_length=32),
        ),
        migrations.AddField(
            model_name='draft',
            name='working_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='kind',
            field=models.CharField(choices=[('document', 'Document'), ('template', 'Template')], default='document', max_length=16),
        ),
        migrations.AlterField(
            model_name='draft',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=16),
        ),
    ]
