def generate_ai_prompt(indicator, requirement, prompt_type='SOP / Policy'):
    """
    Generates a localized prompt for a given evidence requirement.
    Does NOT call any live API.
    """
    
    lab_name = "Al Shifa Laboratory"
    lab_manager = "Dr. Muhammad Munaim Tahir"
    consultant = "Dr. Mubasher Ahmed"
    
    prompt = f"""You are acting as an expert pathology laboratory quality assurance consultant.

Please draft a '{prompt_type}' for {lab_name}.
The document must help the laboratory comply with the Punjab Healthcare Commission (PHC) MSDS standards.

--- CONTEXT ---
Indicator No: {indicator.indicator_no}
Functional Area: {indicator.functional_area_name} ({indicator.functional_area_code})
Standard: {indicator.standard_no} - {indicator.standard_title}

Indicator Text: {indicator.indicator_text}
Compliance Requirement: {indicator.compliance_requirement or 'Not specified'}
Surveyor Check: {indicator.surveyor_check or 'Not specified'}
Scoring Note: {indicator.scoring_note or 'Not specified'}

--- EVIDENCE REQUIREMENT ---
Title: {requirement.title}
Evidence Type: {requirement.get_evidence_type_display()}
Document Type: {requirement.get_document_type_display()}
AI Generation Mode: {requirement.get_ai_generation_mode_display()}

--- REQUIREMENTS ---
1. Provide the complete text in markdown format.
2. Include a header with the Lab Name ({lab_name}).
3. Leave signature lines at the bottom for:
   - Lab Manager / In-charge: {lab_manager}
   - Consultant Pathologist: {consultant}
4. Do NOT mention that this document was generated by an AI.
5. Provide practical, realistic steps suitable for a mid-sized clinical pathology laboratory.
6. The user must review, finalize, and sign the physical copy before uploading it back to the system.

Please generate the draft now.
"""
    return prompt
