# Generated by Django 5.2.14 on 2026-05-18 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, help_text='e.g. Daily, Weekly, Event-based', max_length=50)),
                ('fields_schema', models.JSONField(blank=True, default=dict, help_text='JSON schema for register fields')),
                ('printable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_indicators', models.ManyToManyField(blank=True, related_name='registers', to='indicators.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField()),
                ('values_json', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_registers', to=settings.AUTH_USER_MODEL)),
                ('register_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='registers.registerdefinition')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
