# Generated by Django 4.2.30 on 2026-05-20 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('recurrence_mode', models.CharField(choices=[('STATIC_ONCE', 'Static (Once)'), ('SCHEDULED_RECURRING', 'Scheduled Recurring'), ('EVENT_DRIVEN', 'Event Driven'), ('PER_PATIENT', 'Per Patient'), ('PER_TEST', 'Per Test'), ('PER_EQUIPMENT', 'Per Equipment'), ('PER_EMPLOYEE', 'Per Employee'), ('PER_STOCK_ENTRY', 'Per Stock Entry'), ('NONE', 'None')], default='NONE', max_length=50)),
                ('fields_schema', models.JSONField(default=dict)),
                ('printable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_evidence_requirements', models.ManyToManyField(blank=True, related_name='linked_registers', to='evidence.evidencerequirement')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField()),
                ('values_json', models.JSONField(default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_registers', to=settings.AUTH_USER_MODEL)),
                ('register_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='registers.registerdefinition')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_registers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
