# Generated by Django 5.2.14 on 2026-05-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdefinition',
            name='frequency',
            field=models.CharField(blank=True, help_text='e.g. Daily, Weekly, Monthly, Quarterly, Annual, Event-based', max_length=50),
        ),
    ]
