# Generated by Django 5.2.14 on 2026-05-18 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(choices=[('SOP / Policy', 'SOP / Policy'), ('Register / Logbook', 'Register / Logbook'), ('Recurring Record', 'Recurring Record'), ('Physical Display / Photo', 'Physical Display / Photo'), ('Certificate / License / MOU', 'Certificate / License / MOU'), ('Staff File / HR Record', 'Staff File / HR Record'), ('Patient Record / Reporting System', 'Patient Record / Reporting System'), ('Audit / QA Report', 'Audit / QA Report'), ('Other', 'Other')], default='Other', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='evidence_files/')),
                ('external_url', models.URLField(blank=True, max_length=500, null=True)),
                ('evidence_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_indicators', models.ManyToManyField(blank=True, related_name='evidence_items', to='indicators.indicator')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
