# Generated by Django 4.2.30 on 2026-05-21 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
        ('registers', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('functional_area', models.CharField(blank=True, max_length=50, null=True)),
                ('sequence_order', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=50)),
                ('batch_type', models.CharField(choices=[('GOVERNANCE', 'Governance'), ('SAFETY_EMERGENCY', 'Safety & Emergency'), ('HUMAN_RESOURCE', 'Human Resource'), ('EQUIPMENT_REAGENT', 'Equipment & Reagent'), ('RECORDING_REPORTING', 'Recording & Reporting'), ('QUALITY_ASSURANCE', 'Quality Assurance'), ('BIOSAFETY_WASTE', 'Biosafety & Waste'), ('PATIENT_RIGHTS_ACCESS', 'Patient Rights & Access'), ('MIXED', 'Mixed')], default='MIXED', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Document Batches',
            },
        ),
        migrations.AddField(
            model_name='evidencerequirementfulfillment',
            name='display_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencerequirementfulfillment',
            name='physical_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencerequirementfulfillment',
            name='staff_awareness_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evidencerequirementfulfillment',
            name='status',
            field=models.CharField(choices=[('MISSING', 'Missing'), ('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PARTIAL', 'Partial'), ('READY', 'Ready'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('NOT_APPLICABLE', 'Not Applicable'), ('PLANNED', 'Planned'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=50),
        ),
        migrations.CreateModel(
            name='PlannedEvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('document_kind', models.CharField(choices=[('SOP', 'SOP'), ('POLICY', 'Policy'), ('PROTOCOL', 'Protocol'), ('REGISTER', 'Register'), ('LOGBOOK', 'Logbook'), ('FORM', 'Form'), ('CHECKLIST', 'Checklist'), ('DISPLAY_NOTICE', 'Display Notice'), ('APPOINTMENT_ORDER', 'Appointment Order'), ('AUTHORIZATION_LETTER', 'Authorization Letter'), ('MOU', 'MOU'), ('CERTIFICATE_LICENSE', 'Certificate / License'), ('REPORT', 'Report'), ('AUDIT', 'Audit'), ('LIST_ROSTER', 'List / Roster'), ('PHYSICAL_PROOF', 'Physical Proof'), ('PHOTO_PROOF', 'Photo Proof'), ('TRAINING_RECORD', 'Training Record'), ('DIGITAL_SCREENSHOT', 'Digital Screenshot'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('generation_status', models.CharField(choices=[('PLANNED', 'Planned'), ('DRAFT_NEEDED', 'Draft Needed'), ('DRAFTED', 'Drafted'), ('APPROVED', 'Approved'), ('UPLOADED', 'Uploaded'), ('NOT_APPLICABLE', 'Not Applicable')], default='PLANNED', max_length=50)),
                ('evidence_nature', models.CharField(choices=[('ONE_TIME', 'One-time'), ('RECURRING', 'Recurring'), ('AS_NEEDED', 'As Needed')], default='ONE_TIME', max_length=50)),
                ('frequency', models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUAL', 'Biannual'), ('ANNUAL', 'Annual'), ('AS_NEEDED', 'As Needed')], default='NONE', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('practical_instructions', models.TextField(blank=True, null=True)),
                ('suggested_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_file_section', models.CharField(blank=True, max_length=255, null=True)),
                ('display_location', models.CharField(blank=True, max_length=255, null=True)),
                ('staff_awareness_needed', models.BooleanField(default=False)),
                ('physical_confirmation_needed', models.BooleanField(default=False)),
                ('display_confirmation_needed', models.BooleanField(default=False)),
                ('upload_needed', models.BooleanField(default=True)),
                ('register_entry_needed', models.BooleanField(default=False)),
                ('is_combined_document', models.BooleanField(default=False)),
                ('can_satisfy_multiple_indicators', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_documents', to='evidence.documentbatch')),
                ('evidence_requirements', models.ManyToManyField(blank=True, related_name='planned_documents', to='evidence.evidencerequirement')),
                ('indicators', models.ManyToManyField(blank=True, related_name='planned_documents', to='indicators.indicator')),
                ('linked_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registers.registerdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorEvidenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_evidence_type', models.CharField(choices=[('SOP_POLICY', 'SOP / Policy'), ('FORM_TEMPLATE', 'Form / Template'), ('REGISTER_LOGBOOK', 'Register / Logbook'), ('DISPLAY_NOTICE', 'Display Notice'), ('APPOINTMENT_ORDER', 'Appointment Order'), ('AUTHORIZATION_LETTER', 'Authorization Letter'), ('TRAINING_RECORD', 'Training Record'), ('PHYSICAL_PROOF', 'Physical Proof'), ('PHOTO_EVIDENCE', 'Photo Evidence'), ('LICENSE_CERTIFICATE', 'License / Certificate'), ('MOU_AGREEMENT', 'MOU / Agreement'), ('LIST_ROSTER', 'List / Roster'), ('REPORT_AUDIT', 'Report / Audit'), ('DIGITAL_SYSTEM', 'Digital System'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('upload_required', models.BooleanField(default=False)),
                ('register_required', models.BooleanField(default=False)),
                ('physical_proof_required', models.BooleanField(default=False)),
                ('display_required', models.BooleanField(default=False)),
                ('staff_awareness_required', models.BooleanField(default=False)),
                ('approval_required', models.BooleanField(default=False)),
                ('recurring_required', models.BooleanField(default=False)),
                ('recurrence_frequency', models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIANNUAL', 'Biannual'), ('ANNUAL', 'Annual'), ('AS_NEEDED', 'As Needed')], default='NONE', max_length=50)),
                ('display_location', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_verification_note', models.TextField(blank=True, null=True)),
                ('staff_awareness_note', models.TextField(blank=True, null=True)),
                ('readiness_rule', models.TextField(blank=True, null=True)),
                ('partial_rule', models.TextField(blank=True, null=True)),
                ('missing_rule', models.TextField(blank=True, null=True)),
                ('user_action_prompt', models.TextField(blank=True, null=True)),
                ('ai_mapping_notes', models.TextField(blank=True, null=True)),
                ('profile_confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=50)),
                ('profile_source', models.CharField(choices=[('SEEDED_FROM_RULES', 'Seeded from Rules'), ('AI_ASSISTED', 'AI Assisted'), ('MANUAL_REVIEWED', 'Manual Reviewed'), ('IMPORTED', 'Imported')], default='MANUAL_REVIEWED', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_profile', to='indicators.indicator')),
                ('suggested_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registers.registerdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='source_register_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_evidence_items', to='registers.registerentry'),
        ),
    ]