# Generated by Django 4.2.30 on 2026-05-21 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0002_documentbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenceitem',
            name='planned_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='evidence.plannedevidencedocument'),
        ),
        migrations.CreateModel(
            name='GeneratedEvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_code', models.CharField(max_length=50)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('NEEDS_REVIEW', 'Needs Review'), ('APPROVED_FOR_PRINT', 'Approved for Print'), ('SIGNED_UPLOADED', 'Signed & Uploaded'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('content_markdown', models.TextField()),
                ('output_file', models.FileField(blank=True, null=True, upload_to='generated_drafts/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_print_ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to='evidence.documentbatch')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
                ('linked_evidence_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_source', to='evidence.evidenceitem')),
                ('planned_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_drafts', to='evidence.plannedevidencedocument')),
            ],
        ),
    ]
