# Generated by Django 4.2.30 on 2026-05-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0003_evidenceitem_planned_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedevidencedocument',
            name='docx_file',
            field=models.FileField(blank=True, null=True, upload_to='generated_documents_docx/'),
        ),
        migrations.AddField(
            model_name='generatedevidencedocument',
            name='docx_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedevidencedocument',
            name='docx_status',
            field=models.CharField(choices=[('NOT_GENERATED', 'Not Generated'), ('GENERATED_WAITING_APPROVAL', 'Generated, Waiting for Approval'), ('SIGNED_UPLOADED', 'Signed & Uploaded'), ('NEEDS_REGENERATION', 'Needs Regeneration')], default='NOT_GENERATED', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedevidencedocument',
            name='docx_version',
            field=models.CharField(default='1.0', max_length=20),
        ),
    ]
