# Generated by Django 4.2.30 on 2026-05-22 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_generatedevidencedocument_docx_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencerequirementfulfillment',
            name='register_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
